name: balance
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - ansicolors=1.1.8
  - async-timeout=4.0.3
  - attrs=24.2.0
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - click=8.1.7
  - colorama=0.4.6
  - contourpy=1.2.0
  - cycler=0.12.1
  - entrypoints=0.4
  - fonttools=4.54.1
  - freetype=2.10.4
  - frozenlist=1.5.0
  - greenlet=3.0.1
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - intel-openmp=2023.1.0
  - joblib=1.4.2
  - jpeg=9e
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.45.3
  - libtiff=4.5.1
  - libwebp-base=1.4.0
  - libzlib=1.2.13
  - littleutils=0.2.4
  - llvm-openmp=19.1.2
  - lz4-c=1.9.4
  - matplotlib-base=3.9.2
  - mizani=0.11.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpmath=1.3.0
  - multidict=6.1.0
  - munkres=1.1.4
  - nbclient=0.10.0
  - nbformat=5.10.4
  - ncurses=6.4.20240210
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.4.0
  - outdated=0.2.2
  - packaging=24.1
  - pandas=2.2.2
  - pandas-flavor=0.6.0
  - papermill=2.6.0
  - patsy=0.5.6
  - pillow=10.4.0
  - pingouin=0.5.5
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - plotnine=0.13.6
  - propcache=0.2.0
  - pycparser=2.22
  - pyparsing=3.2.0
  - pysocks=1.7.1
  - python=3.10.15
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.20.0
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.2
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - scikit-learn=1.2.2
  - scipy=1.12.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlalchemy=2.0.34
  - sqlite=3.45.3
  - statsmodels=0.14.4
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.1
  - tqdm=4.67.0
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wheel=0.44.0
  - xarray=2024.9.0
  - xz=5.4.6
  - yaml=0.2.5
  - yarl=1.16.0
  - zeromq=4.3.5
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
    - appnope==0.1.4
    - asttokens==2.4.1
    - babel==2.16.0
    - comm==0.2.2
    - commonmark==0.9.1
    - debugpy==1.8.7
    - decorator==5.1.1
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - faicons==0.2.2
    - great-tables==0.13.0
    - htmltools==0.5.3
    - ipykernel==6.29.5
    - ipython==8.28.0
    - jedi==0.19.1
    - matplotlib-inline==0.1.7
    - mysql-connector-python==9.1.0
    - nest-asyncio==1.6.0
    - parso==0.8.4
    - pexpect==4.9.0
    - prompt-toolkit==3.0.48
    - psutil==6.1.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pygments==2.18.0
    - pymysql==1.1.1
    - pyzmq==26.2.0
    - rpds-py==0.20.0
    - stack-data==0.6.3
    - wcwidth==0.2.13
    - zipp==3.20.2
